USE SCHEMA PUBLIC;
CREATE TABLE EMP_DETAILS
(
   FIRST_NAME STRING,
   LAST_NAME STRING,
);

insert into EMP_DET(FIRST_NAME,LAST_NAME) VALUES ('m','k');
insert into EMP_DET(FIRST_NAME,LAST_NAME) VALUES ('r','k');
insert into EMP_DET(FIRST_NAME,LAST_NAME) VALUES ('gh','km');

